security:
  oauth2:
    client:
      clientId: 0oaf70lltoKb33jYf0h7
      clientSecret: Pb5Nknar4udZewSJvJj0vmaA50wKuO6v6UflzdYp
    resource:
      tokenInfoUri: http://dev-828234.oktapreview.com/oauth2/default/v1/introspect